./time_noload.sh 8
./time_noload.sh 24
./time_noload.sh 48
./time_noload.sh 100
./time_hotpluggedcores.sh 24
./time_hotpluggedcores.sh 48
./time_hotpluggedcores.sh 100
./time_loadedcores.sh 24
./time_loadedcores.sh 48
./time_loadedcores.sh 100
